//
// Created by kassie on 13/01/2026.
//

#ifndef KFLAT_SCANNER_HPP
#define KFLAT_SCANNER_HPP

#include <cstddef>

enum TokenType
{
	TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
	TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
	TOKEN_COMMA, TOKEN_DOT,

	TOKEN_INC, TOKEN_DEC,

	TOKEN_MINUS, TOKEN_PLUS,
	TOKEN_SLASH, TOKEN_STAR,

	TOKEN_SEMICOLON,

	TOKEN_BANG, TOKEN_BANG_EQUAL,
	TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
	TOKEN_GREATER, TOKEN_GREATER_EQUAL,
	TOKEN_LESS, TOKEN_LESS_EQUAL,

	TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

	TOKEN_IF, TOKEN_ELSE,
	TOKEN_AND, TOKEN_OR, TOKEN_TRUE, TOKEN_FALSE,

	TOKEN_CLASS, TOKEN_SUPER, TOKEN_THIS,

	TOKEN_FOR, TOKEN_WHILE,  TOKEN_FUNC,
	TOKEN_PRINT, TOKEN_RETURN, TOKEN_VAR,

	TOKEN_ZILCH, TOKEN_INF,

	TOKEN_ERROR, TOKEN_EOF
  };

struct Token
{
	TokenType type;
	const char* start{};
	size_t length{};
	size_t line{};
};

void initScanner(const char* source);
Token scanToken();

#endif //KFLAT_SCANNER_HPP